apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-center-commander

resources:
  - jaeger.yaml
  - tempo.yaml
  - otel-collector.yaml
  - container-tracing.yaml
  - hpa-custom-metrics.yaml

commonLabels:
  app.kubernetes.io/part-of: data-center-commander
  app.kubernetes.io/component: tracing
  soc.criticality: high
  soc.tier: critical

images:
  - name: jaegertracing/all-in-one
    newTag: 1.62.0
  - name: grafana/tempo
    newTag: 2.6.1
  - name: otel/opentelemetry-collector-contrib
    newTag: 0.109.0

configMapGenerator:
  - name: otel-collector-config
    behavior: merge
    literals:
      - EXPORT_JAEGER=true
      - EXPORT_TEMPO=true
      - EXPORT_SOC=true
