{{- define "trivy-report" -}}
# Trivy Security Report
# Generated: {{ now | date "2006-01-02 15:04:05" }}
# Image: {{ .ArtifactName }}
# Artifact Type: {{ .ArtifactType }}

## Summary

| Severity | Count |
|----------|-------|
| CRITICAL | {{ len (filterSeverity .Results "CRITICAL") }} |
| HIGH | {{ len (filterSeverity .Results "HIGH") }} |
| MEDIUM | {{ len (filterSeverity .Results "MEDIUM") }} |
| LOW | {{ len (filterSeverity .Results "LOW") }} |

## Vulnerabilities

{{- range .Results }}
{{- range .Vulnerabilities }}
### [{{ .Severity }}] {{ .VulnerabilityID }}
- **Package**: {{ .PkgName }} ({{ .InstalledVersion }})
- **Fixed Version**: {{ .FixedVersion }}
- **Title**: {{ .Title }}
- **Description**: {{ .Description }}
- **Severity**: {{ .Severity }}
- **Status**: {{ .Status }}
- **CVSS Score**: {{ .CVSS }}
- **References**: {{ .References }}

{{- end }}
{{- end }}

## Misconfigurations

{{- range .Results }}
{{- range .Misconfigurations }}
### [{{ .Severity }}] {{ .Type }}
- **Title**: {{ .Title }}
- **Description**: {{ .Description }}
- **Message**: {{ .Message }}
- **Resolution**: {{ .Resolution }}
- **Severity**: {{ .Severity }}

{{- end }}
{{- end }}

## Secrets

{{- range .Results }}
{{- range .Secrets }}
### [{{ .Severity }}] {{ .RuleID }}
- **Category**: {{ .Category }}
- **Title**: {{ .Title }}
- **Severity**: {{ .Severity }}
- **Match**: {{ .Match }}

{{- end }}
{{- end }}

## Compliance

{{- range .Results }}
{{- range .Compliance }}
### {{ .ControlID }}
- **Title**: {{ .Title }}
- **Status**: {{ .Status }}
- **Description**: {{ .Description }}

{{- end }}
{{- end }}

---
*Report generated by Trivy {{ .SchemaVersion }}*
{{- end -}}
