const profiles = [
  ["founder", "Solo founder / lab"], ["smb", "SMB / edge estate"],
  ["enterprise", "Large enterprise / hybrid cloud"], ["public", "Government / public sector"],
  ["critical", "Critical / regulated operations"]
];
const key = "dcc-workspace-profile-v1";
const saved = (() => { try { return JSON.parse(localStorage.getItem(key) || "{}"); } catch { return {}; } })();
const style = document.createElement("style");
style.textContent = `.dcc-dialog{width:min(760px,calc(100vw - 28px));max-height:90vh;overflow:auto;background:#101a26;color:#e7eff7;border:1px solid #40556c;border-radius:14px;padding:22px}.dcc-dialog::backdrop{background:#030912cc;backdrop-filter:blur(3px)}.dcc-dialog h2{margin:0 0 8px}.dcc-dialog p,.dcc-dialog li{color:#aebed1}.dcc-dialog .dcc-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.dcc-dialog .dcc-step{border:1px solid #28374a;border-radius:9px;padding:12px}.dcc-dialog label{display:grid;gap:6px;margin:12px 0;color:#c6d5e4}.dcc-dialog select{background:#0c1420;color:#e7eff7;border:1px solid #40556c;border-radius:7px;padding:9px}.dcc-dialog .dcc-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.dcc-graph{width:100%;height:min(66vh,650px);min-height:320px;display:block;background:radial-gradient(ellipse at 50% 0,#152538,#0c1420);border:1px solid #28374a;border-radius:9px}.dcc-node{cursor:pointer}.dcc-node rect{fill:#172638;stroke:#46627b;stroke-width:1.2}.dcc-node text{fill:#e7eff7;font:12px system-ui}.dcc-node .dcc-sub{fill:#92a2b6;font-size:10px}.dcc-edge{stroke:#536980;stroke-width:1.2;opacity:.8}.dcc-edge-label{fill:#92a2b6;font:10px system-ui}.dcc-node.selected rect{stroke:#65d5d0;stroke-width:3}.dcc-node.trace rect{stroke:#ffc86e;stroke-width:2.5}.dcc-node.dim,.dcc-edge.dim{opacity:.12}.dcc-control{max-width:240px}.dcc-meta{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0}.dcc-tag{border:1px solid #354a60;border-radius:99px;padding:3px 8px;color:#b7c8d8;font-size:11px}`;
document.head.append(style);
const dialog = document.createElement("dialog");
dialog.className = "dcc-dialog";
dialog.innerHTML = `<form id="dccSetupForm"><h2>Connect your real estate data</h2><p>This is first-run onboarding. Local preferences do not connect a source, save secrets, or authorize infrastructure changes. Until a source passes its read-only probe and quality gates, operational KPIs remain “not verified.”</p><div class="dcc-steps"><div class="dcc-step"><b>1 · Scope</b><p>Choose your environment and decision objective.</p></div><div class="dcc-step"><b>2 · Connect</b><p>Register an authoritative source with read-only scope.</p></div><div class="dcc-step"><b>3 · Verify</b><p>Probe identity, schema, units, timestamps, coverage and lineage.</p></div></div><label>Organization / environment profile<select name="profile">${profiles.map(([v,l])=>`<option value="${v}" ${saved.profile===v?"selected":""}>${l}</option>`).join("")}</select></label><label>Primary objective<select name="objective"><option value="energy" ${saved.objective==="energy"?"selected":""}>Energy-to-compute and facility efficiency</option><option value="reliability" ${saved.objective==="reliability"?"selected":""}>Reliability and maintenance readiness</option><option value="cost" ${saved.objective==="cost"?"selected":""}>Capacity sizing and unit economics</option><option value="integration" ${saved.objective==="integration"?"selected":""}>Connect real data sources</option></select></label><div class="dcc-meta"><span class="dcc-tag">Synthetic samples are excluded from real-world claims</span><span class="dcc-tag">A configured connector is not a healthy connector</span><span class="dcc-tag">Read-only by default</span></div><h3>Pricing source reality</h3><p>Cloud list prices need a selected SKU, region, usage basis, currency and retrieval date. Azure exposes a public retail-prices API; AWS Price List and Google Cloud Billing Catalog provide public catalog prices but do not establish your negotiated discounts. Hardware, power tariffs, facilities, labor and maintenance require an applicable vendor quote, contract, utility tariff or invoice. Missing and stale prices must stay unpriced.</p><h3>Connection path</h3><ol><li>Open Integrations and select the authoritative vendor/API and data owner.</li><li>Store credentials in the server-side secret manager; never paste keys into this browser.</li><li>Run a read-only probe; validate tenant mapping, units, freshness, quality and lineage.</li><li>Use estimates only when each quantity and dated price has an approved source; otherwise expose the gap.</li></ol><div class="dcc-actions"><button type="button" id="dccSetupCancel">Close</button><button type="button" id="dccOpenIntegrations">Connect a source</button><button type="submit">Save and continue</button></div></form>`;
document.body.append(dialog);
const setup = document.querySelector("#workspaceSetup");
const savedLabel = document.createElement("span"); savedLabel.className="dcc-tag"; savedLabel.id="dccProfileBadge"; setup?.before(savedLabel);
const liveNotice=document.createElement("section");liveNotice.className="banner warn";liveNotice.id="dccLiveNotice";liveNotice.setAttribute("role","status");liveNotice.innerHTML='<b>Live-data boundary:</b> this workspace starts in source-unverified mode. Demo fixtures are not operational telemetry; estimates are not vendor quotes. Connect and verify an authoritative source before using a KPI or price for a decision. <button type="button" id="dccStartOnboarding">Start onboarding</button>';document.querySelector("main.wrap")?.prepend(liveNotice);
function paint(){savedLabel.textContent=saved.profile?`Profile · ${profiles.find(x=>x[0]===saved.profile)?.[1]||saved.profile}`:"Profile · not set";const tier=document.querySelector("#workloadTier"),mapped={public:"government",critical:"mission"}[saved.profile]||saved.profile;if(tier&&mapped){tier.value=mapped;tier.dispatchEvent(new Event("change"))}}
paint();
setup?.addEventListener("click",()=>dialog.showModal());
document.querySelector("#dccStartOnboarding")?.addEventListener("click",()=>dialog.showModal());
if(setup) setup.hidden=false;
if(!saved.saved_at)queueMicrotask(()=>dialog.showModal());
document.querySelector("#dccSetupCancel").addEventListener("click",()=>dialog.close());
document.querySelector("#dccOpenIntegrations").addEventListener("click",()=>{dialog.close();document.querySelector('[data-view="integrations"]')?.click();});
document.querySelector("#dccSetupForm").addEventListener("submit",event=>{event.preventDefault();const form=new FormData(event.currentTarget);saved.profile=String(form.get("profile"));saved.objective=String(form.get("objective"));saved.saved_at=new Date().toISOString();localStorage.setItem(key,JSON.stringify(saved));paint();dialog.close();});
const exportButton=document.createElement("button");exportButton.type="button";exportButton.textContent="Export due-diligence snapshot";document.querySelector(".dcc-actions").prepend(exportButton);
exportButton.addEventListener("click",async()=>{const tenant=new URLSearchParams(location.search).get("tenant_id");const names=["overview","facilities","assets","connectors","analytics","capacity","evidence","costs"];const pack={product:"Data Center Commander",generated_at:new Date().toISOString(),tenant_id:tenant||null,scope:"tenant-scoped read-only snapshot",execution_permitted:false,profile:{organization:saved.profile||null,objective:saved.objective||null,preferences_local_only:true},claims_policy:"Source state and synthetic provenance are reported as returned; this file is not a certification, audit opinion, vendor quote, or production readiness attestation.",sections:{}};await Promise.all(names.map(async name=>{try{const response=await fetch(`/v1/${name}?tenant_id=${encodeURIComponent(tenant||"")}`,{cache:"no-store"}),data=await response.json();pack.sections[name]=response.ok?data:{unavailable:data.error||`HTTP ${response.status}`}}catch(error){pack.sections[name]={unavailable:error.message}}}));const blob=new Blob([JSON.stringify(pack,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="dcc-due-diligence-snapshot.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
