const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const graphHost = document.querySelector("#topologyGraph");
const controlHost = document.querySelector("#topologyControls");
const detailHost = document.querySelector("#topologyDetails");
document.querySelector("#view-assets .module")?.classList.remove("feature-pending");
const styleEl = document.createElement("style"); styleEl.textContent = `.graph-canvas{min-height:320px}.topology-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.topology-toolbar input,.topology-toolbar select{max-width:220px}`; document.head.append(styleEl);
let cached = {nodes:[],edges:[]}, focus = null;
controlHost.innerHTML = `<div class="topology-toolbar"><input id="topologySearch" placeholder="Find asset / type" aria-label="Search graph"><select id="topologyRelation" aria-label="Filter relationship"><option value="">All relationships</option></select><select id="topologyFocus" aria-label="Trace dependency from asset"><option value="">Trace from a node…</option></select><button id="topologyTrace">Trace 2 hops</button></div><div class="muted">Deterministic layered layout · adjacency-list BFS: O(V+E) · render is capped at 200 nodes / 400 edges</div>`;
const search = document.querySelector("#topologySearch"), relation = document.querySelector("#topologyRelation"), focusSelect = document.querySelector("#topologyFocus");
function traceFrom(start, maxDepth=2) { const adjacency=new Map(cached.nodes.map(n=>[n.id,[]])); for(const e of cached.edges){if(adjacency.has(e.source)&&adjacency.has(e.target)){adjacency.get(e.source).push(e.target);adjacency.get(e.target).push(e.source)}} const depth=new Map([[start,0]]),queue=[start]; for(let i=0;i<queue.length;i++){const v=queue[i];if(depth.get(v)>=maxDepth)continue;for(const w of adjacency.get(v)||[])if(!depth.has(w)){depth.set(w,depth.get(v)+1);queue.push(w)}}return new Set(depth.keys()); }
function render() {
 const nodes=cached.nodes.slice(0,200), ids=new Set(nodes.map(n=>n.id)), edges=cached.edges.filter(e=>ids.has(e.source)&&ids.has(e.target)).slice(0,400);
 if(!nodes.length){graphHost.innerHTML='<div class="empty">No asset relationships in this tenant. Register a verified source or load an explicitly synthetic demo dataset.</div>';return}
 const incoming=new Set(edges.map(e=>e.target)),level=new Map(),adj=new Map(nodes.map(n=>[n.id,[]])); for(const e of edges)adj.get(e.source)?.push(e.target);
 const queue=[]; for(const n of nodes)if(!incoming.has(n.id)){level.set(n.id,0);queue.push(n.id)}; for(const n of nodes)if(!level.has(n.id)){level.set(n.id,0);queue.push(n.id)}
 for(let i=0;i<queue.length;i++){const id=queue[i];for(const child of adj.get(id)||[])if(!level.has(child)){level.set(child,level.get(id)+1);queue.push(child)}}
 const columns=new Map();for(const n of nodes){const col=level.get(n.id)||0;if(!columns.has(col))columns.set(col,[]);columns.get(col).push(n)}
 for(const list of columns.values())list.sort((a,b)=>String(a.kind||a.type).localeCompare(String(b.kind||b.type))||String(a.label||a.id).localeCompare(String(b.label||b.id)));
 const width=1200,height=Math.max(360,...[...columns.values()].map(v=>v.length*105+45)),pos=new Map();for(const [col,list]of columns)list.forEach((n,i)=>pos.set(n.id,{x:90+col*300,y:50+(i+1)*height/(list.length+1)}));
 const matched=new Set(traceFrom(focus||"",2)),query=search.value.trim().toLowerCase(),relationValue=relation.value;
 const edgeSvg=edges.filter(e=>!relationValue||e.relation===relationValue).map(e=>{const a=pos.get(e.source),b=pos.get(e.target);return `<g class="${focus&&!matched.has(e.source)&&!matched.has(e.target)?"dcc-edge dim":"dcc-edge"}"><line x1="${a.x+170}" y1="${a.y+27}" x2="${b.x}" y2="${b.y+27}" class="dcc-edge"/><text x="${(a.x+b.x+170)/2}" y="${(a.y+b.y)/2+24}" text-anchor="middle" class="dcc-edge-label">${escapeHtml(e.relation)}</text></g>`}).join("");
 const nodeSvg=nodes.map(n=>{const p=pos.get(n.id),match=!query||`${n.label} ${n.name} ${n.type} ${n.kind} ${n.id}`.toLowerCase().includes(query),isFocus=focus===n.id,isTrace=focus&&matched.has(n.id)&&!isFocus;return `<g class="dcc-node ${isFocus?"selected":""} ${isTrace?"trace":""} ${match?"":"dim"}" data-node="${escapeHtml(n.id)}" tabindex="0" role="button" aria-label="${escapeHtml(n.label||n.name||n.id)}"><rect x="${p.x}" y="${p.y}" width="170" height="55" rx="8"/><text x="${p.x+10}" y="${p.y+21}">${escapeHtml(String(n.label||n.name||n.id).slice(0,24))}</text><text x="${p.x+10}" y="${p.y+41}" class="dcc-sub">${escapeHtml(n.type||n.kind||"asset")} · ${escapeHtml(n.state||n.criticality||"")}</text></g>`}).join("");
 graphHost.innerHTML=`<svg class="dcc-graph" viewBox="0 0 ${width} ${height}" role="img" aria-label="Tenant asset and dependency graph">${edgeSvg}${nodeSvg}</svg>`;
 graphHost.querySelectorAll("[data-node]").forEach(el=>{const select=()=>{focus=el.dataset.node;const item=nodes.find(n=>n.id===focus);const adjacent=edges.filter(e=>e.source===focus||e.target===focus);detailHost.textContent=`${item.label||item.name||item.id} · ${item.type||item.kind||"asset"} · ${adjacent.length} adjacent relationships · ${item.facility||"facility not mapped"} · source: PostgreSQL asset relationship register`;render()};el.addEventListener("click",select);el.addEventListener("keydown",ev=>{if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();select()}})});
}
async function load(){const tenant=new URLSearchParams(location.search).get("tenant_id");if(!tenant){graphHost.innerHTML='<div class="empty">Select a tenant to load tenant-scoped asset relationships.</div>';return}try{const response=await fetch(`/v1/topology?tenant_id=${encodeURIComponent(tenant)}`,{cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);cached={nodes:(data.nodes||[]).map(n=>({...n,id:n.id})),edges:(data.edges||[]).map(e=>({source:e.source,target:e.target,relation:e.relation}))};const rels=[...new Set(cached.edges.map(e=>e.relation))].sort();relation.innerHTML='<option value="">All relationships</option>'+rels.map(r=>`<option value="${escapeHtml(r)}">${escapeHtml(r)}</option>`).join("");focusSelect.innerHTML='<option value="">Trace from a node…</option>'+cached.nodes.map(n=>`<option value="${escapeHtml(n.id)}">${escapeHtml(n.label||n.name||n.id)}</option>`).join("");focus=null;render();}catch(error){graphHost.innerHTML=`<div class="empty">Topology unavailable: ${escapeHtml(error.message)}. Verify the PostgreSQL schema and tenant scope.</div>`}}
search.addEventListener("input",render);relation.addEventListener("change",render);focusSelect.addEventListener("change",()=>{focus=focusSelect.value||null;render()});document.querySelector("#topologyTrace").addEventListener("click",()=>{focus=focusSelect.value||focus;render()});document.querySelector("#refreshTopology").addEventListener("click",load);document.querySelector('[data-view="assets"]')?.addEventListener("click",()=>{if(!cached.nodes.length)load()});
if(location.hash==="#assets")load();
